# Generated by Django 3.2.8 on 2023-07-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivra', '0005_auto_20230713_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
